:linkattrs:
= Red Hat Hello World MSA - Service Mesh

This demo is a *Service Mesh* based implementation of the original
https://cdn.rawgit.com/redhat-helloworld-msa/helloworld-msa/master/readme.html[Red Hat Hello World MSA].

In this demo we will use https://istio.io[Istio] as the Service Mesh framework

== Pre-Requisites

* https://istio.io[Istio] is deployed and configured on the Kubernetes Cluster

The following applications are built and the corresponding docker images are available:

* https://github.com/redhat-developer-demos/istio-api-gateway/blob/master/Istio_README.adoc[Api Gateway]
* https://github.com/redhat-developer-demos/istio-bonjour/blob/master/Istio_README.adoc[Bonjour]
* https://github.com/redhat-developer-demos/istio-aloha/blob/master/Istio_README.adoc[Aloha]
* https://github.com/redhat-developer-demos/istio-hola/blob/master/Istio_README.adoc[Hola]
* https://github.com/redhat-developer-demos/istio-ola/blob/master/Istio_README.adoc[Ola]

[NOTE]
====
Each of the above mentioned applications has a README file called _Istio_README.adoc_ which gives details of building
and deploying the application
====

== Deploying

=== Download and Tag Docker Images

[code,sh]
----
eval $(minikube docker-env) <1>

docker pull kameshsampath/istio-hola:0.0.2
docker tag kameshsampath/istio-hola:0.0.2 hola:0.0.2

docker pull kameshsampath/istio-ola:0.0.2
docker tag kameshsampath/istio-ola:0.0.2 ola:0.0.2

docker pull kameshsampath/istio-aloha:0.0.2
docker tag kameshsampath/istio-aloha:0.0.2 aloha:0.0.2

docker pull kameshsampath/istio-bonjour:0.0.2
docker tag kameshsampath/istio-bonjour:0.0.2 bonjour:0.0.2

docker pull kameshsampath/istio-api-gateway:0.0.2
docker tag kameshsampath/istio-api-gateway:0.0.2 api-gateway:0.0.2
----
<1> make sure the docker images are pulled into kubernetes docker
[NOTE]
====
The version of the application used is *0.0.2* if you have different tags then please edit
link:./redhat-helloworld-msa-all.yaml[redhat-helloworld-msa-all.yaml] to match the right tag
====

=== All in One Deployment

[code,sh]
----
kubectl apply -f istio-redhat-helloworld-msa-all.yaml <1>
----

<1> Deploying application on to Kubernetes

[NOTE]
====
Sometimes depending on the machine power and configuration - some pods might crash, in those cases pelase delete the pod for it to be recreated or you can refer to the `Istio_README.adoc` on each application to deploy them individually.

If you deploy applications individually then you might need to create the ingress using  using `kubectl apply -f redhat-helloworld-msa-ingress.yaml` 
====

=== Define Circuit Breaker

[code,sh]
----
istioctl create -f circuit-breakers/ola-circuit-breaker-policy.yaml <1>
----

<1> Create a default route to ola:0.0.2 service and define the circuit breaker configuration for the same
